package timezone

import "sort"

type abbr struct {
	std      string
	dst      string
	TimeZone string
}

var abbrs = map[string]abbr{
	"Egypt Standard Time":             {"EET", "EET", "Africa/Cairo"},           // "Africa/Cairo"
	"Morocco Standard Time":           {"+00", "+01", "Africa/Casablanca"},      // "Africa/Casablanca"
	"South Africa Standard Time":      {"SAST", "SAST", "Africa/Johannesburg"},  // "Africa/Johannesburg"
	"Sudan Standard Time":             {"CAT", "CAT", "Africa/Khartoum"},        // "Africa/Khartoum"
	"W. Central Africa Standard Time": {"WAT", "WAT", "Africa/Lagos"},           // "Africa/Lagos"
	"E. Africa Standard Time":         {"EAT", "EAT", "Africa/Nairobi"},         // "Africa/Nairobi"
	"Sao Tome Standard Time":          {"GMT", "WAT", "Africa/Sao_Tome"},        // "Africa/Sao_Tome"
	"Libya Standard Time":             {"EET", "EET", "Africa/Tripoli"},         // "Africa/Tripoli"
	"Namibia Standard Time":           {"CAT", "CAT", "Africa/Windhoek"},        // "Africa/Windhoek"
	"Aleutian Standard Time":          {"HST", "HDT", "America/Adak"},           // "America/Adak"
	"Alaskan Standard Time":           {"AKST", "AKDT", "America/Anchorage"},    // "America/Anchorage"
	"Tocantins Standard Time":         {"-03", "-03", "America/Araguaina"},      // "America/Araguaina"
	"Paraguay Standard Time":          {"-04", "-03", "America/Asuncion"},       // "America/Asuncion"
	"Bahia Standard Time":             {"-03", "-03", "America/Bahia"},          // "America/Bahia"
	"SA Pacific Standard Time":        {"-05", "-05", "America/Bogota"},         // "America/Bogota"
	"Argentina Standard Time":         {"-03", "-03", "America/Buenos_Aires"},   // "America/Buenos_Aires"
	"Eastern Standard Time (Mexico)":  {"EST", "EST", "America/Cancun"},         // "America/Cancun"
	"Venezuela Standard Time":         {"-04", "-04", "America/Caracas"},        // "America/Caracas"
	"SA Eastern Standard Time":        {"-03", "-03", "America/Cayenne"},        // "America/Cayenne"
	"Central Standard Time":           {"CST", "CDT", "America/Chicago"},        // "America/Chicago"
	"Mountain Standard Time (Mexico)": {"MST", "MDT", "America/Chihuahua"},      // "America/Chihuahua"
	"Central Brazilian Standard Time": {"-04", "-03", "America/Cuiaba"},         // "America/Cuiaba"
	"Mountain Standard Time":          {"MST", "MDT", "America/Denver"},         // "America/Denver"
	"Greenland Standard Time":         {"-03", "-02", "America/Godthab"},        // "America/Godthab"
	"Turks And Caicos Standard Time":  {"EST", "EDT", "America/Grand_Turk"},     // "America/Grand_Turk"
	"Central America Standard Time":   {"CST", "CST", "America/Guatemala"},      // "America/Guatemala"
	"Atlantic Standard Time":          {"AST", "ADT", "America/Halifax"},        // "America/Halifax"
	"Cuba Standard Time":              {"CST", "CDT", "America/Havana"},         // "America/Havana"
	"US Eastern Standard Time":        {"EST", "EDT", "America/Indianapolis"},   // "America/Indianapolis"
	"SA Western Standard Time":        {"-04", "-04", "America/La_Paz"},         // "America/La_Paz"
	"Pacific Standard Time":           {"PST", "PDT", "America/Los_Angeles"},    // "America/Los_Angeles"
	"Central Standard Time (Mexico)":  {"CST", "CDT", "America/Mexico_City"},    // "America/Mexico_City"
	"Saint Pierre Standard Time":      {"-03", "-02", "America/Miquelon"},       // "America/Miquelon"
	"Montevideo Standard Time":        {"-03", "-03", "America/Montevideo"},     // "America/Montevideo"
	"Eastern Standard Time":           {"EST", "EDT", "America/New_York"},       // "America/New_York"
	"US Mountain Standard Time":       {"MST", "MST", "America/Phoenix"},        // "America/Phoenix"
	"Haiti Standard Time":             {"EST", "EDT", "America/Port-au-Prince"}, // America/"Port"-au-Prince
	"Magallanes Standard Time":        {"-03", "-03", "America/Punta_Arenas"},   // "America/Punta_Arenas"
	"Canada Central Standard Time":    {"CST", "CST", "America/Regina"},         // "America/Regina"
	"Pacific SA Standard Time":        {"-04", "-03", "America/Santiago"},       // "America/Santiago"
	"E. South America Standard Time":  {"-03", "-02", "America/Sao_Paulo"},      // "America/Sao_Paulo"
	"Newfoundland Standard Time":      {"NST", "NDT", "America/St_Johns"},       // "America/St_Johns"
	"Pacific Standard Time (Mexico)":  {"PST", "PDT", "America/Tijuana"},        // "America/Tijuana"
	"Central Asia Standard Time":      {"+06", "+06", "Asia/Almaty"},            // "Asia/Almaty"
	"Jordan Standard Time":            {"EET", "EEST", "Asia/Amman"},            // "Asia/Amman"
	"Arabic Standard Time":            {"+03", "+03", "Asia/Baghdad"},           // "Asia/Baghdad"
	"Azerbaijan Standard Time":        {"+04", "+04", "Asia/Baku"},              // "Asia/Baku"
	"SE Asia Standard Time":           {"+07", "+07", "Asia/Bangkok"},           // "Asia/Bangkok"
	"Altai Standard Time":             {"+07", "+07", "Asia/Barnaul"},           // "Asia/Barnaul"
	"Middle East Standard Time":       {"EET", "EEST", "Asia/Beirut"},           // "Asia/Beirut"
	"India Standard Time":             {"IST", "IST", "Asia/Calcutta"},          // "Asia/Calcutta"
	"Transbaikal Standard Time":       {"+09", "+09", "Asia/Chita"},             // "Asia/Chita"
	"Sri Lanka Standard Time":         {"+0530", "+0530", "Asia/Colombo"},       // "Asia/Colombo"
	"Syria Standard Time":             {"EET", "EEST", "Asia/Damascus"},         // "Asia/Damascus"
	"Bangladesh Standard Time":        {"+06", "+06", "Asia/Dhaka"},             // "Asia/Dhaka"
	"Arabian Standard Time":           {"+04", "+04", "Asia/Dubai"},             // "Asia/Dubai"
	"West Bank Standard Time":         {"EET", "EEST", "Asia/Hebron"},           // "Asia/Hebron"
	"W. Mongolia Standard Time":       {"+07", "+07", "Asia/Hovd"},              // "Asia/Hovd"
	"North Asia East Standard Time":   {"+08", "+08", "Asia/Irkutsk"},           // "Asia/Irkutsk"
	"Israel Standard Time":            {"IST", "IDT", "Asia/Jerusalem"},         // "Asia/Jerusalem"
	"Afghanistan Standard Time":       {"+0430", "+0430", "Asia/Kabul"},         // "Asia/Kabul"
	"Russia Time Zone 11":             {"+12", "+12", "Asia/Kamchatka"},         // "Asia/Kamchatka"
	"Pakistan Standard Time":          {"PKT", "PKT", "Asia/Karachi"},           // "Asia/Karachi"
	"Nepal Standard Time":             {"+0545", "+0545", "Asia/Katmandu"},      // "Asia/Katmandu"
	"North Asia Standard Time":        {"+07", "+07", "Asia/Krasnoyarsk"},       // "Asia/Krasnoyarsk"
	"Magadan Standard Time":           {"+11", "+11", "Asia/Magadan"},           // "Asia/Magadan"
	"N. Central Asia Standard Time":   {"+07", "+07", "Asia/Novosibirsk"},       // "Asia/Novosibirsk"
	"Omsk Standard Time":              {"+06", "+06", "Asia/Omsk"},              // "Asia/Omsk"
	"North Korea Standard Time":       {"KST", "KST", "Asia/Pyongyang"},         // "Asia/Pyongyang"
	"Qyzylorda Standard Time":         {"+05", "+06", "Asia/Qyzylorda"},         // "Asia/Qyzylorda"
	"Myanmar Standard Time":           {"+0630", "+0630", "Asia/Rangoon"},       // "Asia/Rangoon"
	"Arab Standard Time":              {"+03", "+03", "Asia/Riyadh"},            // "Asia/Riyadh"
	"Sakhalin Standard Time":          {"+11", "+11", "Asia/Sakhalin"},          // "Asia/Sakhalin"
	"Korea Standard Time":             {"KST", "KST", "Asia/Seoul"},             // "Asia/Seoul"
	"China Standard Time":             {"CST", "CST", "Asia/Shanghai"},          // "Asia/Shanghai"
	"Singapore Standard Time":         {"+08", "+08", "Asia/Singapore"},         // "Asia/Singapore"
	"Russia Time Zone 10":             {"+11", "+11", "Asia/Srednekolymsk"},     // "Asia/Srednekolymsk"
	"Taipei Standard Time":            {"CST", "CST", "Asia/Taipei"},            // "Asia/Taipei"
	"West Asia Standard Time":         {"+05", "+05", "Asia/Tashkent"},          // "Asia/Tashkent"
	"Georgian Standard Time":          {"+04", "+04", "Asia/Tbilisi"},           // "Asia/Tbilisi"
	"Iran Standard Time":              {"+0330", "+0430", "Asia/Tehran"},        // "Asia/Tehran"
	"Tokyo Standard Time":             {"JST", "JST", "Asia/Tokyo"},             // "Asia/Tokyo"
	"Tomsk Standard Time":             {"+07", "+07", "Asia/Tomsk"},             // "Asia/Tomsk"
	"Ulaanbaatar Standard Time":       {"+08", "+08", "Asia/Ulaanbaatar"},       // "Asia/Ulaanbaatar"
	"Vladivostok Standard Time":       {"+10", "+10", "Asia/Vladivostok"},       // "Asia/Vladivostok"
	"Yakutsk Standard Time":           {"+09", "+09", "Asia/Yakutsk"},           // "Asia/Yakutsk"
	"Ekaterinburg Standard Time":      {"+05", "+05", "Asia/Yekaterinburg"},     // "Asia/Yekaterinburg"
	"Caucasus Standard Time":          {"+04", "+04", "Asia/Yerevan"},           // "Asia/Yerevan"
	"Azores Standard Time":            {"-01", "+00", "Atlantic/Azores"},        // "Atlantic/Azores"
	"Cape Verde Standard Time":        {"-01", "-01", "Atlantic/Cape_Verde"},    // "Atlantic/Cape_Verde"
	"Greenwich Standard Time":         {"GMT", "GMT", "Atlantic/Reykjavik"},     // "Atlantic/Reykjavik"
	"Cen. Australia Standard Time":    {"ACST", "ACDT", "Australia/Adelaide"},   // "Australia/Adelaide"
	"E. Australia Standard Time":      {"AEST", "AEST", "Australia/Brisbane"},   // "Australia/Brisbane"
	"AUS Central Standard Time":       {"ACST", "ACST", "Australia/Darwin"},     // "Australia/Darwin"
	"Aus Central W. Standard Time":    {"+0845", "+0845", "Australia/Eucla"},    // "Australia/Eucla"
	"Tasmania Standard Time":          {"AEST", "AEDT", "Australia/Hobart"},     // "Australia/Hobart"
	"Lord Howe Standard Time":         {"+1030", "+11", "Australia/Lord_Howe"},  // "Australia/Lord_Howe"
	"W. Australia Standard Time":      {"AWST", "AWST", "Australia/Perth"},      // "Australia/Perth"
	"AUS Eastern Standard Time":       {"AEST", "AEDT", "Australia/Sydney"},     // "Australia/Sydney"
	"UTC":                             {"GMT", "GMT", "Etc/GMT"},                // "Etc/GMT"
	"UTC-11":                          {"-11", "-11", "Etc/GMT+11"},             // "Etc/"GMT"+11"
	"Dateline Standard Time":          {"-12", "-12", "Etc/GMT+12"},             // "Etc/"GMT"+12"
	"UTC-02":                          {"-02", "-02", "Etc/GMT+2"},              // "Etc/"GMT"+2"
	"UTC-08":                          {"-08", "-08", "Etc/GMT+8"},              // "Etc/"GMT"+8"
	"UTC-09":                          {"-09", "-09", "Etc/GMT+9"},              // "Etc/"GMT"+9"
	"UTC+12":                          {"+12", "+12", "Etc/GMT-12"},             // "Etc/"GMT"-12"
	"UTC+13":                          {"+13", "+13", "Etc/GMT-13"},             // "Etc/"GMT"-13"
	"Astrakhan Standard Time":         {"+04", "+04", "Europe/Astrakhan"},       // "Europe/Astrakhan"
	"W. Europe Standard Time":         {"CET", "CEST", "Europe/Berlin"},         // "Europe/Berlin"
	"GTB Standard Time":               {"EET", "EEST", "Europe/Bucharest"},      // "Europe/Bucharest"
	"Central Europe Standard Time":    {"CET", "CEST", "Europe/Budapest"},       // "Europe/Budapest"
	"E. Europe Standard Time":         {"EET", "EEST", "Europe/Chisinau"},       // "Europe/Chisinau"
	"Turkey Standard Time":            {"+03", "+03", "Europe/Istanbul"},        // "Europe/Istanbul"
	"Kaliningrad Standard Time":       {"EET", "EET", "Europe/Kaliningrad"},     // "Europe/Kaliningrad"
	"FLE Standard Time":               {"EET", "EEST", "Europe/Kiev"},           // "Europe/Kiev"
	"GMT Standard Time":               {"GMT", "BST", "Europe/London"},          // "Europe/London"
	"Belarus Standard Time":           {"+03", "+03", "Europe/Minsk"},           // "Europe/Minsk"
	"Russian Standard Time":           {"MSK", "MSK", "Europe/Moscow"},          // "Europe/Moscow"
	"Romance Standard Time":           {"CET", "CEST", "Europe/Paris"},          // "Europe/Paris"
	"Russia Time Zone 3":              {"+04", "+04", "Europe/Samara"},          // "Europe/Samara"
	"Saratov Standard Time":           {"+04", "+04", "Europe/Saratov"},         // "Europe/Saratov"
	"Volgograd Standard Time":         {"+04", "+04", "Europe/Volgograd"},       // "Europe/Volgograd"
	"Central European Standard Time":  {"CET", "CEST", "Europe/Warsaw"},         // "Europe/Warsaw"
	"Mauritius Standard Time":         {"+04", "+04", "Indian/Mauritius"},       // "Indian/Mauritius"
	"Samoa Standard Time":             {"+13", "+14", "Pacific/Apia"},           // "Pacific/Apia"
	"New Zealand Standard Time":       {"NZST", "NZDT", "Pacific/Auckland"},     // "Pacific/Auckland"
	"Bougainville Standard Time":      {"+11", "+11", "Pacific/Bougainville"},   // "Pacific/Bougainville"
	"Chatham Islands Standard Time":   {"+1245", "+1345", "Pacific/Chatham"},    // "Pacific/Chatham"
	"Easter Island Standard Time":     {"-06", "-05", "Pacific/Easter"},         // "Pacific/Easter"
	"Fiji Standard Time":              {"+12", "+13", "Pacific/Fiji"},           // "Pacific/Fiji"
	"Central Pacific Standard Time":   {"+11", "+11", "Pacific/Guadalcanal"},    // "Pacific/Guadalcanal"
	"Hawaiian Standard Time":          {"HST", "HST", "Pacific/Honolulu"},       // "Pacific/Honolulu"
	"Line Islands Standard Time":      {"+14", "+14", "Pacific/Kiritimati"},     // "Pacific/Kiritimati"
	"Marquesas Standard Time":         {"-0930", "-0930", "Pacific/Marquesas"},  // "Pacific/Marquesas"
	"Norfolk Standard Time":           {"+11", "+11", "Pacific/Norfolk"},        // "Pacific/Norfolk"
	"West Pacific Standard Time":      {"+10", "+10", "Pacific/Port_Moresby"},   // "Pacific/Port_Moresby"
	"Tonga Standard Time":             {"+13", "+13", "Pacific/Tongatapu"},      // "Pacific/Tongatapu"
}

func ListAbbrs() (timeZones []string) {
	timeZones = make([]string, 0, len(abbrs))
	for key := range abbrs {
		t := key
		timeZones = append(timeZones, t)
	}
	sort.Strings(timeZones)
	return
}
func TimeZone(n int) string {
	tz := ListAbbrs()
	if item, ok := abbrs[tz[n-1]]; ok {
		return item.TimeZone
	}
	return ""
}
